/**
 * Preguntas ROSA - Rapid Office Strain Assessment
 * Estructura de datos para el wizard de evaluación
 */

export const ROSA_SECTIONS = [
  {
    id: "chair",
    section: "Silla",
    icon: "🪑",
    stepLabel: "A",
    questions: [
      {
        id: "seatHeight",
        text: "Altura del asiento",
        desc: "¿El asiento está ajustado a la altura correcta? (rodillas a 90°)",
        field: "seatHeight",
        fieldType: "score", // 1-3 score
        options: ["Correcto (1)", "Incorrecto (2)", "Muy incorrecto (3)"],
        scores: [1, 2, 3],
      },
      {
        id: "seatHeightNoLegRoom",
        text: "Espacio para las piernas",
        desc: "¿La altura permite espacio adecuado para las piernas?",
        field: "seatHeightNoLegRoom",
        fieldType: "boolean",
        options: ["Sí, hay espacio", "No hay espacio suficiente"],
        values: [false, true],
      },
      {
        id: "seatHeightNotAdjustable",
        text: "¿Es el asiento ajustable en altura?",
        desc: "El asiento debe ser ajustable en altura",
        field: "seatHeightNotAdjustable",
        fieldType: "boolean",
        options: ["Sí, es ajustable", "No, no es ajustable"],
        values: [false, true],
      },
      {
        id: "seatDepth",
        text: "Profundidad del asiento",
        desc: "¿Hay espacio suficiente entre el borde del asiento y la parte posterior de las rodillas?",
        field: "seatDepth",
        fieldType: "score",
        options: ["Adecuado (1)", "Inadecuado (2)"],
        scores: [1, 2],
      },
      {
        id: "seatDepthNotAdjustable",
        text: "¿Es el asiento ajustable en profundidad?",
        desc: "La profundidad debe ser ajustable para adaptarse al empleado",
        field: "seatDepthNotAdjustable",
        fieldType: "boolean",
        options: ["Sí, es ajustable", "No, no es ajustable"],
        values: [false, true],
      },
      {
        id: "armrests",
        text: "Brazaletes/Apoyabrazos",
        desc: "¿Los apoyabrazos están ajustados correctamente para soportar los brazos?",
        field: "armrests",
        fieldType: "score",
        options: ["Correcto (1)", "Incorrecto (2)"],
        scores: [1, 2],
      },
      {
        id: "armrestsTooWide",
        text: "¿Los apoyabrazos son demasiado anchos?",
        desc: "Los apoyabrazos no deben obstruir el escritorio",
        field: "armrestsTooWide",
        fieldType: "boolean",
        options: ["No, ancho apropiado", "Sí, demasiado anchos"],
        values: [false, true],
      },
      {
        id: "armrestsNotAdjustable",
        text: "¿Son los apoyabrazos ajustables?",
        desc: "Los apoyabrazos deben ser ajustables en altura",
        field: "armrestsNotAdjustable",
        fieldType: "boolean",
        options: ["Sí, son ajustables", "No, no son ajustables"],
        values: [false, true],
      },
      {
        id: "armrestsSurfaceHard",
        text: "Superficie de apoyabrazos",
        desc: "¿La superficie de los apoyabrazos es dura o incómoda?",
        field: "armrestsSurfaceHard",
        fieldType: "boolean",
        options: ["Cómoda y acolchada", "Dura e incómoda"],
        values: [false, true],
      },
      {
        id: "backrest",
        text: "Respaldo",
        desc: "¿El respaldo proporciona apoyo adecuado a la espalda?",
        field: "backrest",
        fieldType: "score",
        options: ["Adecuado (1)", "Inadecuado (2)"],
        scores: [1, 2],
      },
      {
        id: "backrestNotAdjustable",
        text: "¿Es el respaldo ajustable?",
        desc: "El respaldo debe ser ajustable en inclinación",
        field: "backrestNotAdjustable",
        fieldType: "boolean",
        options: ["Sí, es ajustable", "No, no es ajustable"],
        values: [false, true],
      },
      {
        id: "backrestShouldersRaised",
        text: "Posición del respaldo",
        desc: "¿El respaldo obliga a levantar los hombros?",
        field: "backrestShouldersRaised",
        fieldType: "boolean",
        options: ["No, posición natural", "Sí, requiere levantar hombros"],
        values: [false, true],
      },
      {
        id: "chairUsageTime",
        text: "Tiempo de uso en la silla",
        desc: "¿Cuántas horas al día se usa esta silla?",
        field: "chairUsageTime",
        fieldType: "score",
        options: ["< 2 horas (1)", "2-4 horas (2)", "> 4 horas (3)"],
        scores: [1, 2, 3],
      },
    ],
  },
  {
    id: "screen",
    section: "Pantalla y Teléfono",
    icon: "🖥️",
    stepLabel: "B",
    questions: [
      {
        id: "screen",
        text: "Altura de la pantalla",
        desc: "¿La parte superior del monitor está al nivel de los ojos o ligeramente por debajo?",
        field: "screen",
        fieldType: "score",
        options: ["Correcto (1)", "Incorrecto (2)", "Muy incorrecto (3)"],
        scores: [1, 2, 3],
      },
      {
        id: "screenTilted",
        text: "¿La pantalla está inclinada hacia arriba?",
        desc: "Una inclinación hacia arriba puede causar tensión en el cuello",
        field: "screenTilted",
        fieldType: "boolean",
        options: ["No, está recta", "Sí, está inclinada hacia arriba"],
        values: [false, true],
      },
      {
        id: "screenDocumentsNoHolder",
        text: "¿Hay soporte para documentos de referencia?",
        desc: "Los documentos deben estar al nivel de la pantalla",
        field: "screenDocumentsNoHolder",
        fieldType: "boolean",
        options: ["Sí, hay soporte", "No hay soporte"],
        values: [false, true],
      },
      {
        id: "screenGlare",
        text: "¿Hay reflejo o brillo en la pantalla?",
        desc: "El reflejo puede causar fatiga visual",
        field: "screenGlare",
        fieldType: "boolean",
        options: ["No, buena iluminación", "Sí, hay reflejo o brillo"],
        values: [false, true],
      },
      {
        id: "screenTooFar",
        text: "¿La pantalla está demasiado lejos?",
        desc: "La distancia recomendada es 50-70 cm",
        field: "screenTooFar",
        fieldType: "boolean",
        options: ["Distancia correcta", "Demasiado lejos"],
        values: [false, true],
      },
      {
        id: "screenUsageTime",
        text: "Tiempo mirando la pantalla",
        desc: "¿Cuántas horas al día mira la pantalla?",
        field: "screenUsageTime",
        fieldType: "score",
        options: ["< 4 horas (1)", "> 4 horas (2)", "Variable (3)"],
        scores: [1, 2, 3],
      },
      {
        id: "phone",
        text: "Uso del teléfono",
        desc: "¿Usa teléfono en el puesto de trabajo?",
        field: "phone",
        fieldType: "score",
        options: ["Rara vez (1)", "Frecuentemente (2)"],
        scores: [1, 2],
      },
      {
        id: "phoneNeck",
        text: "¿Usa el teléfono inclinando el cuello?",
        desc: "Esto causa tensión innecesaria en el cuello",
        field: "phoneNeck",
        fieldType: "boolean",
        options: ["No, usa auriculares/manos libres", "Sí, inclina el cuello"],
        values: [false, true],
      },
      {
        id: "phoneNoHandsFree",
        text: "Tipo de uso del teléfono",
        desc: "¿Usa teléfono sin manos libres o auriculares?",
        field: "phoneNoHandsFree",
        fieldType: "boolean",
        options: ["Usa manos libres/auriculares", "No usa manos libres"],
        values: [false, true],
      },
      {
        id: "phoneUsageTime",
        text: "Tiempo de uso del teléfono",
        desc: "¿Cuántas horas al día usa el teléfono?",
        field: "phoneUsageTime",
        fieldType: "score",
        options: ["< 1 hora (1)", "> 1 hora (2)", "Esporádico (3)"],
        scores: [1, 2, 3],
      },
    ],
  },
  {
    id: "peripherals",
    section: "Teclado y Mouse",
    icon: "⌨️",
    stepLabel: "C",
    questions: [
      {
        id: "mouse",
        text: "Posición del mouse",
        desc: "¿El mouse está al mismo nivel que el teclado y cerca del cuerpo?",
        field: "mouse",
        fieldType: "score",
        options: ["Posición correcta (1)", "Posición incorrecta (2)"],
        scores: [1, 2],
      },
      {
        id: "mouseSmall",
        text: "¿El mouse es muy pequeño?",
        desc: "Un mouse muy pequeño causa fatiga en la mano",
        field: "mouseSmall",
        fieldType: "boolean",
        options: ["Tamaño adecuado", "Mouse muy pequeño"],
        values: [false, true],
      },
      {
        id: "mouseDifferentHeight",
        text: "¿El mouse está a diferente altura que el teclado?",
        desc: "Debe estar al mismo nivel para muñeca recta",
        field: "mouseDifferentHeight",
        fieldType: "boolean",
        options: ["Mismo nivel", "Diferente altura"],
        values: [false, true],
      },
      {
        id: "mouseWristPressure",
        text: "¿La muñeca experimenta presión al usar mouse?",
        desc: "Debe mantener muñeca recta sin presión",
        field: "mouseWristPressure",
        fieldType: "boolean",
        options: ["Muñeca recta, sin presión", "Muñeca con presión"],
        values: [false, true],
      },
      {
        id: "mouseUsageTime",
        text: "Tiempo de uso del mouse",
        desc: "¿Cuántas horas al día usa el mouse?",
        field: "mouseUsageTime",
        fieldType: "score",
        options: ["< 4 horas (1)", "> 4 horas (2)", "Variable (3)"],
        scores: [1, 2, 3],
      },
      {
        id: "keyboard",
        text: "Posición del teclado",
        desc: "¿El teclado permite que los codos estén a 90° y muñecas rectas?",
        field: "keyboard",
        fieldType: "score",
        options: ["Posición correcta (1)", "Posición incorrecta (2)"],
        scores: [1, 2],
      },
      {
        id: "keyboardWristDeviated",
        text: "¿La muñeca se desvía al escribir?",
        desc: "Indica una posición incorrecta del teclado",
        field: "keyboardWristDeviated",
        fieldType: "boolean",
        options: ["Muñeca recta", "Muñeca desviada"],
        values: [false, true],
      },
      {
        id: "keyboardTooHigh",
        text: "¿El teclado está demasiado alto?",
        desc: "Esto causa elevación de hombros",
        field: "keyboardTooHigh",
        fieldType: "boolean",
        options: ["Altura correcta", "Demasiado alto"],
        values: [false, true],
      },
      {
        id: "keyboardObjectsOverhead",
        text: "¿Hay objetos encima del teclado?",
        desc: "Objetos sobre el teclado interfieren con la postura",
        field: "keyboardObjectsOverhead",
        fieldType: "boolean",
        options: ["No hay objetos", "Hay objetos sobre el teclado"],
        values: [false, true],
      },
      {
        id: "keyboardNotAdjustable",
        text: "¿Es el teclado ajustable en altura?",
        desc: "Lo ideal es que sea ajustable",
        field: "keyboardNotAdjustable",
        fieldType: "boolean",
        options: ["Sí, es ajustable", "No, no es ajustable"],
        values: [false, true],
      },
      {
        id: "keyboardUsageTime",
        text: "Tiempo de uso del teclado",
        desc: "¿Cuántas horas al día usa el teclado?",
        field: "keyboardUsageTime",
        fieldType: "score",
        options: ["< 4 horas (1)", "> 4 horas (2)", "Variable (3)"],
        scores: [1, 2, 3],
      },
    ],
  },
];

export const RISK_LEVELS = {
  low: { label: "Bajo", color: "text-rosa-low", bg: "bg-rosa-low", className: "text-rosa-low" },
  medium: { label: "Medio", color: "text-rosa-medium", bg: "bg-rosa-medium", className: "text-rosa-medium" },
  high: { label: "Alto", color: "text-rosa-high", bg: "bg-rosa-high", className: "text-rosa-high" },
  veryHigh: { label: "Muy Alto", color: "text-rosa-very-high", bg: "bg-rosa-very-high", className: "text-rosa-very-high" },
};

export function getRiskLevel(score) {
  if (score <= 2) return { ...RISK_LEVELS.low, ring: "#22c55e" };
  if (score <= 5) return { ...RISK_LEVELS.medium, ring: "#f59e0b" };
  if (score <= 7) return { ...RISK_LEVELS.high, ring: "#f97316" };
  return { ...RISK_LEVELS.veryHigh, ring: "#dc2626" };
}
